version: '3.9'

services:
  unsafe_database:
    image: postgres
    ports:
      - "5050:5432"
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
      - ./internal/postgres/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost