version: '3.9'

services:

  default_database:
    image: postgres
    ports:
      - "5050:5432"
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost
  security_database:
    image: postgres
    ports:
      - "5051:5432"
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost